### ISSUE TITLE
Improve ami deployment pipeline

### ISSUE THREAD

**Issue by remkop** [petermr/ami3#24]
With https://github.com/petermr/ami3/issues/20 the ami3 project now has continuous integration: the project is built and the tests are run every time someone pushes changes to master. This ticket is about improving this further.

Note that this ticket is work in progress - some of it is just me thinking out loud.

# Current Deployment Mechanism
The current mechanism for doing an `ami3` release is to build a binary and use the `ami-jars.sh` script to publish the ami jar to a separate `petermr/ami-jars` project.

This involves manually editing the `VERSION` in the `ami-jars.sh` script before running it. It also means there is a separate [ami-jars](https://github.com/petermr/ami-jars) project that contains all past binaries. 

For users to get an ami binary, they need to clone the `ami-jars` project (including all older versions) before they can use the ami version they need.

# Goals
Publish ami jars (potentially including SNAPSHOT jars) to a location where users can get it simply by updating the version number of the ami dependency in their project pom. This means making our ami jar available on Maven Central, Bintray JCenter or GitHub Packages.

Ideally, we want to make this process fully automatic, where the only manual steps are tagging a commit with the release version string and running a command like `mvn deploy` or `mvn publish`.

### Note on version management: 

_Ideally, this tag is the only place where we provide the version number, but this may not be feasible; we may need to put this version string in a file as well, so that it can be displayed when users request version information with `ami --version` and we also want to use this version string when building the ami jar (so the build produces a `ami-0.1-20200406.jar` file)._

# Required Changes
The ami3 project now has two CI jobs in GitHub actions (see #20): 
* one ("Java CI with Maven", defined in `.github/workflows/maven.yml`) that just does the build, runs the test and creates a package (jar)
* another one ("Maven Package", defined in `.github/workflows/mavenpublish.yml`) that "build a package using Maven and then publish it to GitHub packages when a release is created" ([details](https://github.com/actions/setup-java#apache-maven-with-a-settings-path))

Not quite sure yet, but perhaps the latter can do what we want, if we make some minor changes.

* Maven settings [config for authentication](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-apache-maven-for-use-with-github-packages)
* Configuring a [distributionManagement](http://maven.apache.org/plugins/maven-deploy-plugin/usage.html) section in the project `pom.xml`

Alternatively, we can deploy from our local workstation by running `mvn deploy` (requires similar authentication and `distributionManagement` setup).

# Proposed New Release Workflow
The new release workflow will likely be something like this:

* update `version.properties` in the root of the project (this file does not exist currently, we will [reference](http://www.mojohaus.org/properties-maven-plugin/) it in the `pom.xml` to get the jar version number, and we will include it in the ami.jar for printing version info with `ami --version`)
* commit the change, tag this commit with the same version string, and push this commit
* go to the ami project page [Releases tab](https://github.com/petermr/ami3/releases) and [create and publish](https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository) a release for this tag.
  * this will trigger the "Maven Package" CI job set up in GitHub Actions, and should result in the binaries being made available in the [GitHub Packages](https://help.github.com/en/packages/publishing-and-managing-packages/about-github-packages) package hosting service. This may allow us to publish and install packages in GitHub Packages [without needing](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/using-github-packages-with-github-actions) to store and manage a personal access token.
  * alternatively, we can deploy from our local workstation by running `mvn deploy` 

I will need to experiment a bit. Once I worked out all the steps for the new release workflow, I will update BUILDING.md.

**Comment by petermr** [comment]
Great progress

**Comment by remkop** [comment]
Closing, since the work on this ticket and #51 resulted in a package (zipped archive) with launcher scripts and required jars being published to GitHub Packages. Users can download the packages from https://github.com/petermr/ami3/packages/

What is remaining is documentation. I created a separate ticket https://github.com/petermr/ami3/issues/53 for this.
