### ISSUE TITLE
AMIDownload Test fails

### ISSUE THREAD

**Issue by petermr** [petermr/ami3#25]
From Lezan Hawizy:
 have had a look at AMIDownloadTest, these are the errors I found:
A few seem to have an IllegalThreadStateException which i am not sure how to go about testBiorxivSmall() only fails because there is no variable for the landingpage argument on line 67 and its missing a comma between html and pdf in line 68

testBiorxivClimate could be a false assert statement, it's looking for a folder called metadata and file called page1.html, but it's created a __metadata folders instead with under it called resultSetX.html are those the same thing?

**Comment by petermr** [comment]
The @Options / arguments were garbled. Have removed `landingPage` (not sure whether it will be used later ) and added `fulltextFormat` Now runs.

I think `landingPage` may be required for the second phase and so may `fulltextFormat`.

**Comment by petermr** [comment]
>testBiorxivClimate could be a false assert statement, it's looking for a folder called metadata and file called page1.html, but it's created a __metadata folders instead with under it called resultSetX.html are those the same thing?

**Comment by remkop** [comment]
What is the status of this ticket? Can this be closed?
