### ISSUE TITLE
Isolation of function to be used in other projects easily

### ISSUE THREAD

**Issue by frojasg1** [petermr/ami3#38]
Hello,
I have a request:

I have located the function that extracts the bounds of an image in the pdf:
The function is that:

AbstractPageParser  -> getBoundingRect()

I have tried to isolate it in one single class, so I can use it in a project of mine without the need to add the whole dependency of ami3 to my project.
But I have found many dependencies, I finally I was not able to isolate it.

Would it be easy to isolate it?
Would you do that for me if it is not difficult?

Thank you very much!

**Comment by frojasg1** [comment]
Sorry, I have found the issue with my code, so I do not need to use ami3 function.

**Comment by remkop** [comment]
Closing as per @frojasg1's comment.
