### ISSUE TITLE
Default values not working in `ami` commands

### ISSUE THREAD

**Issue by petermr** [petermr/ami3#42]

**Comment by remkop** [comment]
Can you provide some detail on how to reproduce the issue?

**Comment by petermr** [comment]
This is  probably a misreading of the `picocli` spec.

I want to have `monochrome` as an Option with a value, which is omitted can default to a default value
```
    @Option(names = {"--monochrome"},
    		arity="0..1",
    		defaultValue = "monochrome",
            description = "FILTER: move monochrome images to <monochrome>; default ${DEFAULT-VALUE}; "+_DELETE+" means delete"
            )
	private MonochromeDest monochromeDirname;
```
and called by
```
	@Test
	/** 
	 * 
	 */
	public void testImageForestPlotsSmall() throws Exception {
		String cmd = ""
				+ " -p "+FOREST_PLOT_SMALL
				+ " image"
				+ " --monochrome"     // note value missing
				+ " --minwidth 100"
				+ " --minheight 100"
				+ " --smalldir small"   // explicit value
				;
		AMIImageTool imageTool = AMI.execute(AMIImageTool.class, cmd);
	} 
```
gives:
```
Invalid value for option '--monochrome': expected one of [_delete, monochrome] (case-sensitive) but was '--monochromedir'
Usage: ami image [OPTIONS]
Try 'ami image --help' for more information.
```

**Comment by petermr** [comment]
Gosh! you were too quick!

**Comment by petermr** [comment]
Thanks,
I know you advised against  `arity="0..1"` and I have removed this almost everywhere.
I will now take your advice completely!

The idea was:
```
user omitted the --monochrome option altogether
user specified --monochrome with a parameter
user specified --monochrome without parameter
```
1. do not take `monochrome` action at all 
2. use `monochrome` with the given parameter
3. use `monochrome` with the default value

In this case, do we need these 3 cases to behave differently?

Yes. The main reason is that it's easy to misspell or misremember parameters.

But In this and other cases I favour convention-over-configuration and so will make the choices simpler by not giving them.

**Comment by remkop** [comment]
Closing: this was fixed by using `fallbackValue = "monochrome"`  instead of `defaultValue`.
